name: smart_farm_app
description: Smart Farm Flutter app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0                   # updated version
  shared_preferences: ^2.4.0      # updated version
  shimmer: ^3.0.0
  lottie: ^3.2.0                  # updated version
  fl_chart: ^1.1.1                # updated version
  geolocator: 14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0           # updated lints version

flutter:
  uses-material-design: true
  assets:
    - assets/loading.json
    - assets/welcome.json
